site_name: The Price of Revenge
site_description: The Price of Revenge
site_url: https://valentine195.github.io/Obsidian-Vault/

theme:
    name: "material"
    logo: assets/logo/favicons.png
    favicon: assets/logo/favicons.png
    custom_dir: overrides
    font:
        text: Karla
        code: Ubuntu Mono
    language: en
    palette:
        # Light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: teal
          accent: light blue
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode

        # Dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    features:
        - navigation.indexes
# Extensions
markdown_extensions:
    - footnotes
    - nl2br
    - attr_list
    - sane_lists
    - meta
    - smarty
    - tables
    - mdx_breakless_lists
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.details
    - pymdownx.magiclink
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - admonition
    - toc:
          permalink: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
plugins:
    - search
    - ezlinks:
          wikilinks: true
    - awesome-pages
    - embed_file
extra_javascript:
    - assets/js/mathjax.js
    - assets/js/utils.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - assets/js/tooltipster.bundle.js
extra_css:
    - assets/css/img-grids-floats.css
    - assets/css/utils.css
    - assets/css/custom_attributes.css
    - assets/css/tooltipster.bundle.min.css
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
extra:
    generator: false
